# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - radianceai

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://americanexpress.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4e03dee0fc67480f8deef2c2b73f7456 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_5bde1bcbaf794bf9944b02609e4c2f60 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: americanexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4e03dee0fc67480f8deef2c2b73f7456 }}/radianceai:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'radianceai'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ec07f8e92ee14ce2a627387b596bd846 }}
        images: 'americanexpress.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4e03dee0fc67480f8deef2c2b73f7456 }}/radianceai:${{ github.sha }}'